-- LISTAR: nombre y cargo de la tabla EMPLEADO y DEPARTAMENTO al que pertenece.

SELECT EMPLEADO.NOMBRE, EMPLEADO.CARGO, DEPARTAMENTO.DNOM AS DEPARTAMENTO
FROM EMPLEADO INNER JOIN DEPARTAMENTO
ON EMPLEADO.DEPT_NO = DEPARTAMENTO.DEPT_NO
ORDER BY DNOM ASC;

-- Devuelve un listado con los Detalles de las ventas (todos los atributos) y la Descricpión del Producto.

SELECT DETALLE.*, PRODUCTO.DESCRIPCION
FROM DETALLE INNER JOIN PRODUCTO
ON DETALLE.PRODUCTO_NUMERO = PRODUCTO.PRODUCTO_NUMERO
ORDER BY PRODUCTO_NUMERO;