SELECT * FROM CLIENTES C WHERE C.CODIGOPOBLACION IN
(SELECT P.CODIGOPOBLACION FROM POBLACIONES P WHERE P.POBLACION LIKE "%FERROL%");

poblacion y numero de habitantes que esten por encima de la media de habitantes

SELECT POBLACION, HABITANTES FROM POBLACIONES WHERE HABITANTES >=
(SELECT AVG(HABITANTES) FROM POBLACIONES);