SELECT C.CLIENTE_CODIGO, C.NOMBRE, P.FECHA_ENVIO AS "ENVIO"
FROM CLIENTE C, PEDIDO P 
WHERE C.CLIENTE_CODIGO = P.CLIENTE_CODIGO
ORDER BY CLIENTE_CODIGO;

SELECT C.CLIENTE_CODIGO, C.NOMBRE, P.FECHA_ENVIO AS "ENVIO"
FROM CLIENTE C INNER JOIN PEDIDO P
ON C.CLIENTE_CODIGO = P.CLIENTE_CODIGO
ORDER BY CLIENTE_CODIGO;

SELECT C.CLIENTE_CODIGO, C.NOMBRE, P.FECHA_ENVIO AS "ENVIO"
FROM CLIENTE C JOIN PEDIDO P
ON C.CLIENTE_CODIGO = P.CLIENTE_CODIGO
ORDER BY CLIENTE_CODIGO;

SELECT C.CLIENTE_CODIGO, C.NOMBRE, P.FECHA_ENVIO AS "ENVIO"
FROM CLIENTE C NATURAL JOIN PEDIDO P
ORDER BY CLIENTE_CODIGO;