SELECT NOMBRE, GASTOS
FROM DEPARTAMENTO
WHERE GASTOS <= 5000;

SELECT NOMBRE
FROM DEPARTAMENTO
WHERE PRESUPUESTO NOT BETWEEN 100000 AND 200000;

SELECT NOMBRE, GASTOS, PRESUPUESTO
FROM DEPARTAMENTO
WHERE GASTOS > PRESUPUESTO;

SELECT NOMBRE, GASTOS, PRESUPUESTO
FROM DEPARTAMENTO
WHERE GASTOS = PRESUPUESTO;